package runtime

import (
	"crypto/rand"
	"fmt"
	"html"
	"math/big"
	"path/filepath"
	"strconv"
	"strings"
)

// phpIniSearchDirs are candidate locations of the php.ini templates shipped
// inside the official FrankenPHP archive.
var phpIniSearchDirs = []string{"php.ini-production", "php.ini-development", "php.ini"}

// BuildPHPIni derives a session php.ini from the archive's production
// template and appends the extensions phpMyAdmin requires. The extension_dir
// is given as an absolute path because FrankenPHP resolves it against the
// runtime layout on Windows.
func (m *Manager) BuildPHPIni(runtimeDir string) (string, error) {
	var base []byte
	var readErr error
	for _, candidate := range phpIniSearchDirs {
		base, readErr = m.fsys.ReadFile(filepath.Join(runtimeDir, candidate))
		if readErr == nil {
			break
		}
	}
	if readErr != nil {
		base = []byte("; generated php.ini for phpMyAdmin Desktop\n")
	}

	var b strings.Builder
	b.Write(base)
	if len(base) > 0 && !strings.HasSuffix(string(base), "\n") {
		b.WriteString("\n")
	}
	b.WriteString("\n; phpMyAdmin Desktop session overrides\n")
	b.WriteString(fmt.Sprintf("extension_dir = \"%s\"\n", strings.ReplaceAll(filepath.Join(runtimeDir, "ext"), "\\", "\\\\")))
	for _, ext := range []string{"curl", "mbstring", "mysqli", "openssl", "pdo_mysql", "zip"} {
		b.WriteString("extension=" + ext + "\n")
	}
	// phpMyAdmin's import form is constrained by both upload_max_filesize and
	// post_max_size. Keep the latter slightly larger for multipart overhead.
	b.WriteString("upload_max_filesize = 10G\n")
	b.WriteString("post_max_size = 10241M\n")
	return b.String(), nil
}

// BuildCaddyfile returns a classic-mode FrankenPHP site bound strictly to
// loopback. PHP configuration is selected by the child process's PHPRC
// environment variable, not inside php_server: current FrankenPHP releases
// reject ini_file_path as a php_server subdirective. The admin API is disabled
// so no extra local port is opened.
func BuildCaddyfile(host string, port int, pmaDir string) string {
	return fmt.Sprintf(`{
	admin off
}

http://%s:%d {
	root * %s
	php_server
}
`, host, port, quoteCaddyPath(pmaDir))
}

// quoteCaddyPath emits a single Caddyfile token for an absolute filesystem
// path. Windows app-data directories commonly contain spaces (for example
// "phpMyAdmin Desktop"); without quoting, Caddy parses the path as several
// root directive arguments and refuses to start. JSON-style double quotes
// are accepted by the Caddyfile adapter and preserve Windows backslashes.
func quoteCaddyPath(path string) string {
	return strconv.Quote(path)
}

func BlowfishSecret() (string, error) {
	const alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	var b strings.Builder
	for b.Len() < 32 {
		n, err := rand.Int(rand.Reader, big.NewInt(int64(len(alphabet))))
		if err != nil {
			return "", err
		}
		b.WriteByte(alphabet[n.Int64()])
	}
	return b.String(), nil
}

// BuildPMAConfig renders a per-session config-auth configuration. The host/port
// pair intentionally points at the loopback placeholder 127.0.0.1:3306 here:
// the concrete database endpoint is written per-session by
// ApplyServerToPMAConfig. The database username and password from servers.json
// are written into this private, per-session config so phpMyAdmin authenticates
// automatically; SSH credentials are never written to it.
func BuildPMAConfig(secret, username, password string) string {
	return fmt.Sprintf(`<?php
/* Generated by phpMyAdmin Desktop. Do not edit by hand. */
declare(strict_types=1);

$cfg['blowfish_secret'] = '%s';
$i = 0;
$i++;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['user'] = '%s';
$cfg['Servers'][$i]['password'] = '%s';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
`, escapePMAConfigValue(secret), escapePMAConfigValue(username), escapePMAConfigValue(password))
}

func escapePMAConfigValue(value string) string {
	return strings.ReplaceAll(strings.ReplaceAll(value, `\`, `\\`), `'`, `\'`)
}

// ApplyServerToPMAConfig rewrites the host/port directives of the generated
// config for a concrete connection. The port is always written explicitly —
// including 3306 — so the served config documents its real endpoint instead
// of relying on phpMyAdmin's implicit default. The host is either the
// configured direct host or the SSH tunnel's loopback endpoint with its
// ephemeral port. Authentication directives come from BuildPMAConfig.
func ApplyServerToPMAConfig(config string, host string, port int) string {
	config = strings.Replace(config,
		"$cfg['Servers'][$i]['host'] = '127.0.0.1';",
		fmt.Sprintf("$cfg['Servers'][$i]['host'] = '%s';", escapePMAConfigValue(host)), 1)
	if port <= 0 {
		port = 3306
	}
	config = strings.Replace(config,
		"$cfg['Servers'][$i]['port'] = '3306';",
		fmt.Sprintf("$cfg['Servers'][$i]['port'] = '%d';", port), 1)
	return config
}

// ApplyThemeToPMAConfig enables the bundled Darkwolf theme. It must only be
// called after the theme is present in the session's phpMyAdmin themes
// directory; otherwise phpMyAdmin would fall back to its bundled default and
// this directive would misdescribe the session.
func ApplyThemeToPMAConfig(config, theme string) string {
	return strings.Replace(config,
		"$cfg['Servers'][$i]['extension'] = 'mysqli';",
		fmt.Sprintf("$cfg['Servers'][$i]['extension'] = 'mysqli';\n$cfg['ThemeDefault'] = '%s';", escapePMAConfigValue(theme)), 1)
}

// ScrubForDiagnostics removes any occurrence of the provided secret values
// from a diagnostic string so generated logs can never echo credentials.
func ScrubForDiagnostics(text string, secrets ...string) string {
	for _, secret := range secrets {
		if secret == "" {
			continue
		}
		text = strings.ReplaceAll(text, secret, "[redacted]")
		text = strings.ReplaceAll(text, html.EscapeString(secret), "[redacted]")
	}
	return text
}
