// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the bound application service. Keep all calls that touch local
 * configuration or the filesystem in this service; the Solid frontend must not
 * access the host directly.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

export function CheckLatestVersion(componentID: string): $CancellablePromise<string[]> {
    return $Call.ByName("main.App.CheckLatestVersion", componentID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ChoosePrivateKey opens the platform file picker at ~/.ssh when available.
 */
export function ChoosePrivateKey(): $CancellablePromise<string> {
    return $Call.ByName("main.App.ChoosePrivateKey");
}

/**
 * FindServerName resolves a connection name for window composition.
 */
export function FindServerName(serverID: string): $CancellablePromise<string> {
    return $Call.ByName("main.App.FindServerName", serverID);
}

/**
 * GetServerID identifies the selected connection when this process was launched
 * specifically for that connection.
 */
export function GetServerID(): $CancellablePromise<string> {
    return $Call.ByName("main.App.GetServerID");
}

/**
 * GetServersJSON returns the persisted connection catalogue. Credentials are
 * stored locally by the existing config-store implementation.
 */
export function GetServersJSON(): $CancellablePromise<string> {
    return $Call.ByName("main.App.GetServersJSON");
}

/**
 * NewWindow starts a second app process for a selected connection, preserving
 * the original process-per-connection design.
 */
export function NewWindow(serverID: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.NewWindow", serverID);
}

/**
 * SaveServersJSON persists the connection catalogue exactly as supplied by the
 * frontend. Validation belongs in the connection form when it is implemented.
 */
export function SaveServersJSON(value: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.SaveServersJSON", value);
}

/**
 * SessionReconnectTunnel reconnects an active SSH tunnel on its existing local
 * loopback port. It deliberately does not restart the phpMyAdmin runtime.
 */
export function SessionReconnectTunnel(): $CancellablePromise<void> {
    return $Call.ByName("main.App.SessionReconnectTunnel");
}

/**
 * SessionStart installs/reuses the runtime, optionally opens the SSH tunnel,
 * starts the FrankenPHP child process and returns the loopback URL the
 * frontend navigates to. Only available in a dedicated -serverId process.
 */
export function SessionStart(): $CancellablePromise<string> {
    return $Call.ByName("main.App.SessionStart");
}

/**
 * SessionStatus exposes the session phase for progress rendering.
 */
export function SessionStatus(): $CancellablePromise<string> {
    return $Call.ByName("main.App.SessionStatus");
}

/**
 * SessionStop tears down the session runtime and tunnel. It is idempotent.
 */
export function SessionStop(): $CancellablePromise<void> {
    return $Call.ByName("main.App.SessionStop");
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
