// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the bound application service. Keep all calls that touch local
 * configuration or the filesystem in this service; the Solid frontend must not
 * access the host directly.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

export function CheckLatestVersion(componentID: string): $CancellablePromise<string[]> {
    return $Call.ByName("main.App.CheckLatestVersion", componentID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ChoosePrivateKey opens the platform file picker at ~/.ssh when available.
 */
export function ChoosePrivateKey(): $CancellablePromise<string> {
    return $Call.ByName("main.App.ChoosePrivateKey");
}

/**
 * GetServerID identifies the selected connection when this process was launched
 * specifically for that connection.
 */
export function GetServerID(): $CancellablePromise<string> {
    return $Call.ByName("main.App.GetServerID");
}

/**
 * GetServersJSON returns the persisted connection catalogue. Credentials are
 * stored locally by the existing config-store implementation.
 */
export function GetServersJSON(): $CancellablePromise<string> {
    return $Call.ByName("main.App.GetServersJSON");
}

/**
 * NewWindow starts a second app process for a selected connection, preserving
 * the original process-per-connection design.
 */
export function NewWindow(serverID: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.NewWindow", serverID);
}

/**
 * SaveServersJSON persists the connection catalogue exactly as supplied by the
 * frontend. Validation belongs in the connection form when it is implemented.
 */
export function SaveServersJSON(value: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.SaveServersJSON", value);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
