// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChoosePrivateKey():Promise<string>;

export function GetServerID():Promise<string>;

export function NewWindow(arg1:string):Promise<void>;
