// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChoosePrivateKey() {
  return window['go']['main']['App']['ChoosePrivateKey']();
}

export function GetServerID() {
  return window['go']['main']['App']['GetServerID']();
}

export function NewWindow(arg1) {
  return window['go']['main']['App']['NewWindow'](arg1);
}
